server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: html



